### ISSUE TITLE
Annotate unused exports 

### ISSUE THREAD

**Issue by gitcoindev** [Codex-/knip-reporter#8]
Hi @Codex-  , I was able to enable knip-reporter to annotate also unused exports directly in the source files by extending buildArraySection.

See a demo screenshot here:

![Screenshot from 2023-11-28 12-23-08](https://github.com/Codex-/knip-reporter/assets/88761781/90c2a4e1-a8b9-4043-b7aa-734bffcbb186)

Please let me know if you'd be interested to pull it into upstream. I would clean it up a bit and open a PR then.

**Comment by Codex-** [comment]
Sounds great, I've been meaning to add this so a PR to add this would be welcomed :)

**Comment by gitcoindev** [comment]
All right! I will prepare and open a PR until Friday EOD

**Comment by Codex-** [comment]
Currently being implemented, along with `types` and `duplicates` support. See #16

**Comment by gitcoindev** [comment]
> Currently being implemented, along with `types` and `duplicates` support. See #16 

Great news! I will test and integrate this as soon as you merge.

**Comment by Codex-** [comment]
Completed, releasd with `v2.1.0`. `v2` tag has been updated to the latest `v2` version :)
